### ISSUE TITLE
Not an Issue: Cannot remove items from cart

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-71/bangazon-api-ctrl-alt-elite#34]
If the user has products currently in the cart, and then clicks on the trash icon to remove it, it is not removed from the cart.

**Comment by Caleb-Ford-93** [comment]
Might be meant to reference the Delete Order button at bottom of Cart view? When clicked, remove all items from cart?

**Comment by Caleb-Ford-93** [comment]
Please improve this help request

**Comment by tylerosmond** [comment]
consider this bug squashed
