### ISSUE TITLE
Bug: Products keep getting added to the last, closed order

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-71/bangazon-api-ctrl-alt-elite#4]
Steps to reproduce.

1. Authenticate the client and get a token
1. Create a payment type
1. Add a product to the cart by sending a POST request to `http://localhost:8000/profile/cart`
1. Finish the order by sending a PUT request to the order's URL
1. Add a product to the cart by sending a POST request to `http://localhost:8000/profile/cart`

At this point, the product is being related to the completed order instead of a new one being generated.

**Comment by Caleb-Ford-93** [comment]
Upon testing, it seems that adding products to an order is in fact not working at all, not even getting the issue outlined in this ticket.  I'm going to back up and fix that, then ensure that products are getting added to an open order (or creating a new order if there is no open order)
