### ISSUE TITLE
¯\\_(ツ)_/¯

### ISSUE THREAD

**Issue by Caleb-Ford-93** [NSS-Day-Cohort-71/bangazon-api-ctrl-alt-elite#56]
¯\\_(ツ)_/¯

_Originally posted by @tylerosmond in https://github.com/NSS-Day-Cohort-71/bangazon-api-ctrl-alt-elite/issues/55#issuecomment-2394079251_
            

What is this?

**Comment by tylerosmond** [comment]
( ͡° ͜ʖ ͡°) · ദ്ദി( • ᴗ - ) · ≽^•⩊•^≼
